image:
  file: .gitpod.Dockerfile
ports:
    - port: 3000
      onOpen: open-preview
    - port: 5432
      onOpen: ignore
tasks:
    - init: >
        (cp -n .env.example .env || true) && 
        pipenv install &&
        psql -U gitpod -c 'CREATE DATABASE example;' &&
        psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d example &&
        pipenv run init && 
        pipenv run migrate && 
        pipenv run upgrade
      command: >
        pipenv run start;
    - command: python3 welcome.py
      openMode: split-right

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: false
