"""empty message

Revision ID: 17672f0586b2
Revises: 32e374566b62
Create Date: 2021-05-29 11:20:39.062999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17672f0586b2'
down_revision = '32e374566b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('long_description', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'long_description')
    # ### end Alembic commands ###
