"""empty message

Revision ID: 5101b292090f
Revises: 17672f0586b2
Create Date: 2021-07-18 13:43:24.476999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5101b292090f'
down_revision = '17672f0586b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_password_token', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_password_token')
    # ### end Alembic commands ###
